# Generated by Django 3.1.7 on 2021-09-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail_basic',
            name='thumb_basic',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbnail_enterprise',
            name='thumb_enterprise',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='thumbnail_premium',
            name='thumb_premium',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
