# Generated by Django 3.1.7 on 2021-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210918_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail_enterprise',
            name='thumb_enterprise',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='thumbnail_premium',
            name='thumb_premium',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
