# Generated by Django 3.1.7 on 2021-09-18 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_thumbnail_basic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail_enterprise',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thumbnail_premium',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thumbnail_basic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
