# Generated by Django 3.1.7 on 2021-09-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210917_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_200', models.URLField(blank=True, null=True)),
                ('thumb_400', models.URLField(blank=True, null=True)),
                ('thumb_original', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.images')),
            ],
        ),
    ]
