# Generated by Django 3.1.7 on 2021-09-18 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20210918_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbnail_Premium',
            new_name='Thumbnail_200',
        ),
        migrations.RenameModel(
            old_name='Thumbnail_Basic',
            new_name='Thumbnail_400',
        ),
        migrations.RenameModel(
            old_name='Thumbnail_Enterprise',
            new_name='Thumbnail_Original',
        ),
        migrations.RenameField(
            model_name='thumbnail_200',
            old_name='thumb_premium',
            new_name='thumb_200',
        ),
        migrations.RenameField(
            model_name='thumbnail_400',
            old_name='thumb_basic',
            new_name='thumb_400',
        ),
        migrations.RenameField(
            model_name='thumbnail_original',
            old_name='thumb_enterprise',
            new_name='thumb_original',
        ),
    ]
