# Generated by Django 3.1.7 on 2021-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
