# Generated by Django 3.1.7 on 2021-09-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210919_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thumbnail_Original',
        ),
    ]
