# Generated by Django 3.1.7 on 2021-09-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210917_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail_200',
            old_name='image',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='thumbnail_400',
            old_name='image',
            new_name='image_id',
        ),
        migrations.RenameField(
            model_name='thumbnail_original',
            old_name='image',
            new_name='image_id',
        ),
    ]
